import type { Category } from "./api";

export interface MasterItem {
  name: string;
  group: string;
  groupEmoji: string;
  category: Category;
  defaultExpiryDays: number;
}

export const GROUPS = [
  { name: "すべて",   emoji: "🗂"  },
  { name: "野菜",     emoji: "🥬"  },
  { name: "きのこ",   emoji: "🍄"  },
  { name: "芋類",     emoji: "🥔"  },
  { name: "魚介",     emoji: "🐟"  },
  { name: "肉類",     emoji: "🥩"  },
  { name: "卵・乳",   emoji: "🥚"  },
  { name: "調味料",   emoji: "🧂"  },
  { name: "スパイス", emoji: "🌶️" },
  { name: "食用油",   emoji: "🫙"  },
  { name: "缶詰",     emoji: "🥫"  },
  { name: "レトルト", emoji: "🍱"  },
  { name: "冷凍品",   emoji: "🧊"  },
  { name: "飲み物",   emoji: "🥤"  },
] as const;

export const FOOD_MASTER: MasterItem[] = [
  // ── 野菜（葉物・茎・花）────────────────────────
  { name: "あしたば",     group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 3  },
  { name: "アスパラガス", group: "野菜", groupEmoji: "🌱", category: "vegetable", defaultExpiryDays: 5  },
  { name: "アーティチョーク", group: "野菜", groupEmoji: "🌸", category: "vegetable", defaultExpiryDays: 7 },
  { name: "キャベツ",     group: "野菜", groupEmoji: "🥬", category: "vegetable", defaultExpiryDays: 7  },
  { name: "白菜",         group: "野菜", groupEmoji: "🥬", category: "vegetable", defaultExpiryDays: 7  },
  { name: "ほうれん草",   group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 4  },
  { name: "小松菜",       group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 4  },
  { name: "レタス",       group: "野菜", groupEmoji: "🥗", category: "vegetable", defaultExpiryDays: 5  },
  { name: "春菊",         group: "野菜", groupEmoji: "🌼", category: "vegetable", defaultExpiryDays: 4  },
  { name: "ブロッコリー", group: "野菜", groupEmoji: "🥦", category: "vegetable", defaultExpiryDays: 5  },
  { name: "カリフラワー", group: "野菜", groupEmoji: "🥦", category: "vegetable", defaultExpiryDays: 7  },
  { name: "チンゲンサイ", group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 5  },
  { name: "にら",         group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 5  },
  { name: "ねぎ",         group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 7  },
  { name: "セロリ",       group: "野菜", groupEmoji: "🌱", category: "vegetable", defaultExpiryDays: 7  },
  { name: "オクラ",       group: "野菜", groupEmoji: "🫛", category: "vegetable", defaultExpiryDays: 4  },
  { name: "みずな",       group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 4  },
  { name: "みつば",       group: "野菜", groupEmoji: "🍃", category: "vegetable", defaultExpiryDays: 4  },
  { name: "ルッコラ",     group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 4  },
  { name: "パセリ",       group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 5  },
  { name: "シソ",         group: "野菜", groupEmoji: "🍃", category: "vegetable", defaultExpiryDays: 4  },
  { name: "モロヘイヤ",   group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 3  },
  { name: "つるむらさき", group: "野菜", groupEmoji: "🌸", category: "vegetable", defaultExpiryDays: 3  },
  { name: "空芯菜",       group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 3  },
  { name: "クレソン",     group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 3  },
  { name: "なばな",       group: "野菜", groupEmoji: "🌸", category: "vegetable", defaultExpiryDays: 3  },
  { name: "タアサイ",     group: "野菜", groupEmoji: "🥬", category: "vegetable", defaultExpiryDays: 4  },
  { name: "みょうが",     group: "野菜", groupEmoji: "🌺", category: "vegetable", defaultExpiryDays: 5  },
  { name: "からし菜",     group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 4  },
  { name: "おかひじき",   group: "野菜", groupEmoji: "🌱", category: "vegetable", defaultExpiryDays: 3  },
  { name: "ふき",         group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 3  },
  { name: "ふだん草",     group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 4  },
  { name: "チコリー",     group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 5  },
  { name: "トレビス",     group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 5  },
  { name: "コールラビ",   group: "野菜", groupEmoji: "🥬", category: "vegetable", defaultExpiryDays: 7  },
  // ── 野菜（実野菜・果菜）──────────────────────
  { name: "トマト",       group: "野菜", groupEmoji: "🍅", category: "vegetable", defaultExpiryDays: 5  },
  { name: "なす",         group: "野菜", groupEmoji: "🍆", category: "vegetable", defaultExpiryDays: 5  },
  { name: "きゅうり",     group: "野菜", groupEmoji: "🥒", category: "vegetable", defaultExpiryDays: 5  },
  { name: "ピーマン",     group: "野菜", groupEmoji: "🫑", category: "vegetable", defaultExpiryDays: 7  },
  { name: "ズッキーニ",   group: "野菜", groupEmoji: "🥒", category: "vegetable", defaultExpiryDays: 7  },
  { name: "かぼちゃ",     group: "野菜", groupEmoji: "🎃", category: "vegetable", defaultExpiryDays: 30 },
  { name: "とうもろこし", group: "野菜", groupEmoji: "🌽", category: "vegetable", defaultExpiryDays: 3  },
  { name: "ゴーヤ",       group: "野菜", groupEmoji: "🥒", category: "vegetable", defaultExpiryDays: 5  },
  { name: "冬瓜",         group: "野菜", groupEmoji: "🥒", category: "vegetable", defaultExpiryDays: 30 },
  { name: "ししとう",     group: "野菜", groupEmoji: "🫑", category: "vegetable", defaultExpiryDays: 5  },
  { name: "うり",         group: "野菜", groupEmoji: "🥒", category: "vegetable", defaultExpiryDays: 5  },
  { name: "とうがらし",   group: "野菜", groupEmoji: "🌶️", category: "vegetable", defaultExpiryDays: 7 },
  { name: "さやいんげん", group: "野菜", groupEmoji: "🫛", category: "vegetable", defaultExpiryDays: 4  },
  { name: "さやえんどう", group: "野菜", groupEmoji: "🫛", category: "vegetable", defaultExpiryDays: 4  },
  { name: "そらまめ",     group: "野菜", groupEmoji: "🫘", category: "vegetable", defaultExpiryDays: 3  },
  { name: "枝豆",         group: "野菜", groupEmoji: "🫘", category: "vegetable", defaultExpiryDays: 3  },
  { name: "グリーンピース", group: "野菜", groupEmoji: "🫘", category: "vegetable", defaultExpiryDays: 3 },
  { name: "かいわれ大根", group: "野菜", groupEmoji: "🌱", category: "vegetable", defaultExpiryDays: 4  },
  // ── 野菜（根菜・鱗茎）────────────────────────
  { name: "大根",         group: "野菜", groupEmoji: "🥕", category: "vegetable", defaultExpiryDays: 10 },
  { name: "にんじん",     group: "野菜", groupEmoji: "🥕", category: "vegetable", defaultExpiryDays: 14 },
  { name: "玉ねぎ",       group: "野菜", groupEmoji: "🧅", category: "vegetable", defaultExpiryDays: 30 },
  { name: "ごぼう",       group: "野菜", groupEmoji: "🥕", category: "vegetable", defaultExpiryDays: 10 },
  { name: "れんこん",     group: "野菜", groupEmoji: "🪷", category: "vegetable", defaultExpiryDays: 7  },
  { name: "かぶ",         group: "野菜", groupEmoji: "🫛", category: "vegetable", defaultExpiryDays: 7  },
  { name: "にんにく",     group: "野菜", groupEmoji: "🧄", category: "vegetable", defaultExpiryDays: 30 },
  { name: "しょうが",     group: "野菜", groupEmoji: "🫚", category: "vegetable", defaultExpiryDays: 14 },
  { name: "たけのこ",     group: "野菜", groupEmoji: "🎋", category: "vegetable", defaultExpiryDays: 3  },
  { name: "らっきょう",   group: "野菜", groupEmoji: "🧅", category: "vegetable", defaultExpiryDays: 7  },
  { name: "ビーツ",       group: "野菜", groupEmoji: "🫐", category: "vegetable", defaultExpiryDays: 14 },
  { name: "うど",         group: "野菜", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 5  },
  { name: "エシャロット", group: "野菜", groupEmoji: "🧅", category: "vegetable", defaultExpiryDays: 14 },
  { name: "くわい",       group: "野菜", groupEmoji: "🌰", category: "vegetable", defaultExpiryDays: 7  },
  { name: "ゆり根",       group: "野菜", groupEmoji: "🌷", category: "vegetable", defaultExpiryDays: 7  },
  { name: "やまのいも",   group: "野菜", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 14 },
  { name: "ヤーコン",     group: "野菜", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 14 },
  { name: "食用菊",       group: "野菜", groupEmoji: "🌸", category: "vegetable", defaultExpiryDays: 3  },
  // ── 芋類（じゃがいも） ───────────────────────
  { name: "じゃがいも",   group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 30 },
  { name: "メークイン",   group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 30 },
  { name: "男爵いも",     group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 30 },
  { name: "きたあかり",   group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 30 },
  { name: "新じゃが",     group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 14 },
  // ── 芋類（さつまいも） ───────────────────────
  { name: "さつまいも",   group: "芋類", groupEmoji: "🍠", category: "vegetable", defaultExpiryDays: 30 },
  { name: "安納芋",       group: "芋類", groupEmoji: "🍠", category: "vegetable", defaultExpiryDays: 21 },
  { name: "紅はるか",     group: "芋類", groupEmoji: "🍠", category: "vegetable", defaultExpiryDays: 21 },
  { name: "鳴門金時",     group: "芋類", groupEmoji: "🍠", category: "vegetable", defaultExpiryDays: 21 },
  { name: "紫芋",         group: "芋類", groupEmoji: "🍠", category: "vegetable", defaultExpiryDays: 21 },
  // ── 芋類（さといも） ─────────────────────────
  { name: "さといも",     group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 14 },
  { name: "八頭",         group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 14 },
  { name: "えびいも",     group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 10 },
  // ── 芋類（長芋・山芋） ───────────────────────
  { name: "長芋",         group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 14 },
  { name: "大和芋",       group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 14 },
  { name: "自然薯",       group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 14 },
  { name: "つくね芋",     group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 14 },
  // ── 芋類（こんにゃく） ───────────────────────
  { name: "こんにゃく",   group: "芋類", groupEmoji: "🥔", category: "fridge",    defaultExpiryDays: 14 },
  { name: "しらたき",     group: "芋類", groupEmoji: "🥔", category: "fridge",    defaultExpiryDays: 14 },
  { name: "板こんにゃく", group: "芋類", groupEmoji: "🥔", category: "fridge",    defaultExpiryDays: 14 },
  { name: "くわい",       group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 14 },
  { name: "きくいも",     group: "芋類", groupEmoji: "🥔", category: "vegetable", defaultExpiryDays: 10 },
  // ── きのこ類 ──────────────────────────────────
  { name: "しいたけ",     group: "きのこ", groupEmoji: "🍄", category: "vegetable", defaultExpiryDays: 5  },
  { name: "しめじ",       group: "きのこ", groupEmoji: "🌰", category: "vegetable", defaultExpiryDays: 5  },
  { name: "えのきたけ",   group: "きのこ", groupEmoji: "🌾", category: "vegetable", defaultExpiryDays: 7  },
  { name: "エリンギ",     group: "きのこ", groupEmoji: "🌱", category: "vegetable", defaultExpiryDays: 7  },
  { name: "まいたけ",     group: "きのこ", groupEmoji: "🍂", category: "vegetable", defaultExpiryDays: 5  },
  { name: "マッシュルーム", group: "きのこ", groupEmoji: "🟤", category: "vegetable", defaultExpiryDays: 5 },
  { name: "ひらたけ",     group: "きのこ", groupEmoji: "🌿", category: "vegetable", defaultExpiryDays: 5  },
  { name: "なめこ",       group: "きのこ", groupEmoji: "🟡", category: "vegetable", defaultExpiryDays: 5  },
  { name: "きくらげ",     group: "きのこ", groupEmoji: "🖤", category: "vegetable", defaultExpiryDays: 7  },
  { name: "松茸",         group: "きのこ", groupEmoji: "🎋", category: "vegetable", defaultExpiryDays: 3  },
  // ── 魚介類 ────────────────────────────────────
  { name: "マグロ",       group: "魚介", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 2 },
  { name: "カツオ",       group: "魚介", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 2 },
  { name: "サバ",         group: "魚介", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 2 },
  { name: "アジ",         group: "魚介", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 2 },
  { name: "イワシ",       group: "魚介", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 2 },
  { name: "タイ",         group: "魚介", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 2 },
  { name: "サーモン（鮭）", group: "魚介", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 2 },
  { name: "タラ",         group: "魚介", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 2 },
  { name: "ブリ",         group: "魚介", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 2 },
  { name: "ウナギ",       group: "魚介", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 2 },
  { name: "ヒラメ",       group: "魚介", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 2 },
  { name: "スズキ",       group: "魚介", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 2 },
  { name: "アサリ",       group: "魚介", groupEmoji: "🦪", category: "fridge", defaultExpiryDays: 2 },
  { name: "ハマグリ",     group: "魚介", groupEmoji: "🦪", category: "fridge", defaultExpiryDays: 2 },
  { name: "シジミ",       group: "魚介", groupEmoji: "🦪", category: "fridge", defaultExpiryDays: 2 },
  { name: "ホタテ",       group: "魚介", groupEmoji: "🦪", category: "fridge", defaultExpiryDays: 2 },
  { name: "カキ",         group: "魚介", groupEmoji: "🦪", category: "fridge", defaultExpiryDays: 2 },
  { name: "エビ",         group: "魚介", groupEmoji: "🦐", category: "fridge", defaultExpiryDays: 2 },
  { name: "カニ",         group: "魚介", groupEmoji: "🦀", category: "fridge", defaultExpiryDays: 2 },
  { name: "イカ",         group: "魚介", groupEmoji: "🦑", category: "fridge", defaultExpiryDays: 2 },
  { name: "タコ",         group: "魚介", groupEmoji: "🐙", category: "fridge", defaultExpiryDays: 2 },
  // ── 肉類（牛） ────────────────────────────────
  { name: "牛肉（薄切り）", group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "牛こま切れ",   group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 2 },
  { name: "牛ひき肉",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 2 },
  { name: "牛バラ肉",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "牛肩ロース",   group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "牛ロース",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "牛サーロイン", group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "牛ステーキ",   group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "牛もも肉",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "牛ランプ",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "牛タン",       group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "牛カルビ",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "牛スジ",       group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 2 },
  // ── 肉類（豚） ────────────────────────────────
  { name: "豚肉（薄切り）", group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "豚こま切れ",   group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 2 },
  { name: "豚ひき肉",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 2 },
  { name: "豚バラ肉",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "豚ロース",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "豚肩ロース",   group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "豚もも肉",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "豚ヒレ肉",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "豚スペアリブ", group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "豚タン",       group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "豚ハラミ",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "豚レバー",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 2 },
  // ── 肉類（鶏） ────────────────────────────────
  { name: "鶏もも肉",     group: "肉類", groupEmoji: "🍗", category: "fridge", defaultExpiryDays: 3 },
  { name: "鶏胸肉",       group: "肉類", groupEmoji: "🍗", category: "fridge", defaultExpiryDays: 3 },
  { name: "鶏ひき肉",     group: "肉類", groupEmoji: "🍗", category: "fridge", defaultExpiryDays: 2 },
  { name: "鶏ささみ",     group: "肉類", groupEmoji: "🍗", category: "fridge", defaultExpiryDays: 3 },
  { name: "鶏手羽先",     group: "肉類", groupEmoji: "🍗", category: "fridge", defaultExpiryDays: 3 },
  { name: "鶏手羽元",     group: "肉類", groupEmoji: "🍗", category: "fridge", defaultExpiryDays: 3 },
  { name: "鶏皮",         group: "肉類", groupEmoji: "🍗", category: "fridge", defaultExpiryDays: 2 },
  { name: "鶏レバー",     group: "肉類", groupEmoji: "🍗", category: "fridge", defaultExpiryDays: 2 },
  { name: "鶏砂肝",       group: "肉類", groupEmoji: "🍗", category: "fridge", defaultExpiryDays: 2 },
  { name: "鶏ハツ",       group: "肉類", groupEmoji: "🍗", category: "fridge", defaultExpiryDays: 2 },
  // ── 肉類（合挽き・その他） ───────────────────
  { name: "合挽き肉",     group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 2 },
  { name: "馬肉",         group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 2 },
  { name: "鹿肉",         group: "肉類", groupEmoji: "🦌", category: "fridge", defaultExpiryDays: 3 },
  { name: "鴨肉",         group: "肉類", groupEmoji: "🦆", category: "fridge", defaultExpiryDays: 3 },
  { name: "ラム肉",       group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  { name: "イノシシ肉",   group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 3 },
  // ── 肉類（加工肉） ────────────────────────────
  { name: "ベーコン",     group: "肉類", groupEmoji: "🥓", category: "fridge", defaultExpiryDays: 7  },
  { name: "ウインナー",   group: "肉類", groupEmoji: "🌭", category: "fridge", defaultExpiryDays: 7  },
  { name: "ソーセージ",   group: "肉類", groupEmoji: "🌭", category: "fridge", defaultExpiryDays: 7  },
  { name: "チョリソー",   group: "肉類", groupEmoji: "🌭", category: "fridge", defaultExpiryDays: 7  },
  { name: "サラミ",       group: "肉類", groupEmoji: "🍕", category: "fridge", defaultExpiryDays: 14 },
  { name: "ロースハム",   group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 5  },
  { name: "生ハム",       group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 5  },
  { name: "ハム",         group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 5  },
  { name: "焼豚",         group: "肉類", groupEmoji: "🥩", category: "fridge", defaultExpiryDays: 5  },
  { name: "ランチョンミート", group: "肉類", groupEmoji: "🥩", category: "pantry", defaultExpiryDays: 180 },
  // ── 魚肉加工品 ────────────────────────────────
  { name: "かまぼこ",     group: "肉類", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 5  },
  { name: "ちくわ",       group: "肉類", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 5  },
  { name: "はんぺん",     group: "肉類", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 5  },
  { name: "さつま揚げ",   group: "肉類", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 5  },
  { name: "魚肉ソーセージ", group: "肉類", groupEmoji: "🌭", category: "fridge", defaultExpiryDays: 14 },
  { name: "カニカマ",     group: "肉類", groupEmoji: "🦀", category: "fridge", defaultExpiryDays: 7  },
  { name: "なると",       group: "肉類", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 7  },
  { name: "明太子",       group: "肉類", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 3  },
  { name: "たらこ",       group: "肉類", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 3  },
  { name: "いくら",       group: "肉類", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 3  },
  { name: "スモークサーモン", group: "肉類", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 7 },
  { name: "アンチョビ",   group: "肉類", groupEmoji: "🐟", category: "fridge", defaultExpiryDays: 14 },
  // ── 卵・乳製品 ────────────────────────────────
  { name: "卵",           group: "卵・乳", groupEmoji: "🥚", category: "fridge", defaultExpiryDays: 14 },
  { name: "牛乳",         group: "卵・乳", groupEmoji: "🥛", category: "fridge", defaultExpiryDays: 7  },
  { name: "バター",       group: "卵・乳", groupEmoji: "🧈", category: "fridge", defaultExpiryDays: 30 },
  { name: "チーズ",       group: "卵・乳", groupEmoji: "🧀", category: "fridge", defaultExpiryDays: 14 },
  { name: "ヨーグルト",   group: "卵・乳", groupEmoji: "🥛", category: "fridge", defaultExpiryDays: 7  },
  { name: "生クリーム",   group: "卵・乳", groupEmoji: "🥛", category: "fridge", defaultExpiryDays: 5  },
  { name: "豆腐",         group: "卵・乳", groupEmoji: "⬜", category: "fridge", defaultExpiryDays: 5  },
  { name: "納豆",         group: "卵・乳", groupEmoji: "🫘", category: "fridge", defaultExpiryDays: 7  },
  { name: "絹豆腐",       group: "卵・乳", groupEmoji: "⬜", category: "fridge", defaultExpiryDays: 5  },
  // ── 調味料 ────────────────────────────────────
  { name: "醤油（濃口）", group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 180 },
  { name: "醤油（薄口）", group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 180 },
  { name: "白だし",       group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 90  },
  { name: "みりん",       group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 180 },
  { name: "料理酒",       group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 180 },
  { name: "味噌（米）",   group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 90  },
  { name: "味噌（赤）",   group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 90  },
  { name: "白味噌",       group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 60  },
  { name: "穀物酢",       group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 365 },
  { name: "米酢",         group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 365 },
  { name: "黒酢",         group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 365 },
  { name: "バルサミコ酢", group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 365 },
  { name: "ポン酢",       group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 90  },
  { name: "オイスターソース", group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 90 },
  { name: "ケチャップ",   group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 90  },
  { name: "マヨネーズ",   group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 60  },
  { name: "上白糖",       group: "調味料", groupEmoji: "🍯", category: "fridge", defaultExpiryDays: 365 },
  { name: "三温糖",       group: "調味料", groupEmoji: "🍯", category: "fridge", defaultExpiryDays: 365 },
  { name: "黒砂糖",       group: "調味料", groupEmoji: "🍯", category: "fridge", defaultExpiryDays: 365 },
  { name: "てんさい糖",   group: "調味料", groupEmoji: "🍯", category: "fridge", defaultExpiryDays: 365 },
  { name: "塩（精製）",   group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 365 },
  { name: "天日塩",       group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 365 },
  { name: "岩塩",         group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 365 },
  { name: "藻塩",         group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 365 },
  { name: "豆板醤",       group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 180 },
  { name: "コチュジャン", group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 180 },
  { name: "テンメンジャン", group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 180 },
  { name: "中濃ソース",   group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 180 },
  { name: "ウスターソース", group: "調味料", groupEmoji: "🧂", category: "fridge", defaultExpiryDays: 365 },
  // ── 食用油 ────────────────────────────────────
  { name: "サラダ油",     group: "食用油", groupEmoji: "🫙", category: "fridge", defaultExpiryDays: 180 },
  { name: "ごま油",       group: "食用油", groupEmoji: "🫙", category: "fridge", defaultExpiryDays: 180 },
  { name: "オリーブオイル", group: "食用油", groupEmoji: "🫙", category: "fridge", defaultExpiryDays: 365 },
  { name: "えごま油",     group: "食用油", groupEmoji: "🫙", category: "fridge", defaultExpiryDays: 90  },
  { name: "なたね油",     group: "食用油", groupEmoji: "🫙", category: "fridge", defaultExpiryDays: 180 },
  { name: "ラード",       group: "食用油", groupEmoji: "🫙", category: "fridge", defaultExpiryDays: 90  },
  // ── スパイス ──────────────────────────────────
  { name: "ブラックペパー", group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 365 },
  { name: "ホワイトペパー", group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 365 },
  { name: "カレーパウダー", group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 365 },
  { name: "ガラムマサラ",  group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 365 },
  { name: "クミン",       group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 365 },
  { name: "コリアンダー", group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "ターメリック", group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 365 },
  { name: "パプリカパウダー", group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 365 },
  { name: "シナモン",     group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "ナツメグ",     group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "オレガノ",     group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "バジル",       group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "ローズマリー", group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "タイム",       group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "ローリエ",     group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "山椒",         group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 365 },
  { name: "七味唐辛子",   group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 365 },
  { name: "鷹の爪",       group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 365 },
  { name: "わさび",       group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 30  },
  { name: "柚子こしょう", group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 60  },
  { name: "クローブ",     group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "カルダモン",   group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "フェンネル",   group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "ディル",       group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "サフラン",     group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "オールスパイス", group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "スターアニス（八角）", group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },
  { name: "花椒（ホアジャオ）", group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 365 },
  { name: "チリパウダー", group: "スパイス", groupEmoji: "🌶️", category: "fridge", defaultExpiryDays: 365 },
  { name: "マスタード",   group: "スパイス", groupEmoji: "🌿", category: "fridge", defaultExpiryDays: 365 },

  // ── 缶詰（水産）────────────────────────────────
  { name: "ツナ缶",         group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "さば缶（水煮）", group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "さば缶（みそ）", group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "いわし缶",       group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "さんま缶",       group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "さけ缶",         group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "かに缶",         group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "ほたて缶",       group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "あさり缶",       group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  // ── 缶詰（野菜・果実）──────────────────────────
  { name: "トマト缶（ホール）", group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "トマト缶（カット）", group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "スイートコーン缶", group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "マッシュルーム缶", group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "大豆缶",         group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "ひよこ豆缶",     group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "ゆであずき缶",   group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "みかん缶",       group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "もも缶",         group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "パイナップル缶", group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  // ── 缶詰（肉・その他）──────────────────────────
  { name: "コンビーフ缶",   group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "やきとり缶",     group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "ランチョンミート缶", group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "コーンスープ缶", group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  { name: "カレー缶",       group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 365 },
  // ── びん詰 ────────────────────────────────────
  { name: "鮭フレーク",     group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 180 },
  { name: "のりつくだに",   group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 180 },
  { name: "なめたけ（瓶）", group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 180 },
  { name: "メンマ（瓶）",   group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 180 },
  { name: "オリーブ（瓶）", group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 180 },
  { name: "ピクルス",       group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 180 },
  { name: "いちごジャム",   group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 180 },
  { name: "マーマレード",   group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 180 },
  { name: "ブルーベリージャム", group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 180 },
  { name: "栗の甘露煮",     group: "缶詰", groupEmoji: "🥫", category: "pantry", defaultExpiryDays: 180 },

  // ── レトルト食品 ──────────────────────────────
  { name: "カレー（ビーフ）",   group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "カレー（チキン）",   group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "カレー（ポーク）",   group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "スープカレー",       group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "シチュー（クリーム）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "シチュー（コーン）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "ハヤシライスの素",   group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "ミートソース（レトルト）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "クリームソース（レトルト）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "パスタソース（ペペロンチーノ）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "コーンスープ（レトルト）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "ポタージュ",         group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "マーボー豆腐の素",   group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "八宝菜の素",         group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "おでんの素",         group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "丼の素（牛丼）",     group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "丼の素（親子丼）",   group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "かまめしの素",       group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "デミグラスソース",   group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "ホワイトソース（レトルト）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  // ── レトルト米飯 ──────────────────────────────
  { name: "パックご飯（白飯）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 365 },
  { name: "パックご飯（玄米）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 365 },
  { name: "五目めし（パック）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 365 },
  { name: "赤飯（パック）",     group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 365 },
  { name: "おかゆ（レトルト）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 365 },
  { name: "チキンライス（パック）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 365 },
  { name: "チャーハン（パック）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 365 },
  // ── レトルト肉・魚 ────────────────────────────
  { name: "ハンバーグ（レトルト）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "ミートボール（レトルト）", group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "ウナギのかば焼き",   group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "さんまのかば焼き",   group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },
  { name: "エビクリーム煮",     group: "レトルト", groupEmoji: "🍱", category: "pantry", defaultExpiryDays: 180 },

  // ── 冷凍食品 ──────────────────────────────────
  { name: "冷凍餃子",       group: "冷凍品", groupEmoji: "🥟", category: "freezer", defaultExpiryDays: 60 },
  { name: "冷凍シュウマイ", group: "冷凍品", groupEmoji: "🥟", category: "freezer", defaultExpiryDays: 60 },
  { name: "冷凍唐揚げ",     group: "冷凍品", groupEmoji: "🍗", category: "freezer", defaultExpiryDays: 60 },
  { name: "冷凍ハンバーグ", group: "冷凍品", groupEmoji: "🍔", category: "freezer", defaultExpiryDays: 60 },
  { name: "冷凍コロッケ",   group: "冷凍品", groupEmoji: "🍞", category: "freezer", defaultExpiryDays: 60 },
  { name: "冷凍エビフライ", group: "冷凍品", groupEmoji: "🦐", category: "freezer", defaultExpiryDays: 60 },
  { name: "冷凍グラタン",   group: "冷凍品", groupEmoji: "🫕", category: "freezer", defaultExpiryDays: 60 },
  { name: "お好み焼き（冷凍）", group: "冷凍品", groupEmoji: "🥞", category: "freezer", defaultExpiryDays: 60 },
  { name: "たこ焼き（冷凍）", group: "冷凍品", groupEmoji: "🐙", category: "freezer", defaultExpiryDays: 60 },
  { name: "ピザ（冷凍）",   group: "冷凍品", groupEmoji: "🍕", category: "freezer", defaultExpiryDays: 60 },
  { name: "冷凍うどん",     group: "冷凍品", groupEmoji: "🍜", category: "freezer", defaultExpiryDays: 60 },
  { name: "冷凍ラーメン",   group: "冷凍品", groupEmoji: "🍜", category: "freezer", defaultExpiryDays: 60 },
  { name: "冷凍チャーハン", group: "冷凍品", groupEmoji: "🍚", category: "freezer", defaultExpiryDays: 60 },
  { name: "冷凍パスタ",     group: "冷凍品", groupEmoji: "🍝", category: "freezer", defaultExpiryDays: 60 },
  // 冷凍野菜
  { name: "冷凍ブロッコリー",   group: "冷凍品", groupEmoji: "🥦", category: "freezer", defaultExpiryDays: 90 },
  { name: "冷凍ほうれんそう",   group: "冷凍品", groupEmoji: "🌿", category: "freezer", defaultExpiryDays: 90 },
  { name: "冷凍ミックス野菜",   group: "冷凍品", groupEmoji: "🥗", category: "freezer", defaultExpiryDays: 90 },
  { name: "冷凍枝豆",           group: "冷凍品", groupEmoji: "🫛", category: "freezer", defaultExpiryDays: 90 },
  { name: "冷凍コーン",         group: "冷凍品", groupEmoji: "🌽", category: "freezer", defaultExpiryDays: 90 },
  { name: "冷凍いんげん",       group: "冷凍品", groupEmoji: "🫘", category: "freezer", defaultExpiryDays: 90 },
  { name: "冷凍かぼちゃ",       group: "冷凍品", groupEmoji: "🎃", category: "freezer", defaultExpiryDays: 90 },
  // 冷凍シーフード・肉
  { name: "冷凍えび",           group: "冷凍品", groupEmoji: "🦐", category: "freezer", defaultExpiryDays: 90 },
  { name: "冷凍シーフードミックス", group: "冷凍品", groupEmoji: "🦑", category: "freezer", defaultExpiryDays: 90 },
  { name: "冷凍ホタテ",         group: "冷凍品", groupEmoji: "🦪", category: "freezer", defaultExpiryDays: 90 },
  { name: "冷凍鶏むね肉",       group: "冷凍品", groupEmoji: "🍗", category: "freezer", defaultExpiryDays: 90 },
  { name: "冷凍ミンチ肉",       group: "冷凍品", groupEmoji: "🥩", category: "freezer", defaultExpiryDays: 60 },
  { name: "アイスクリーム",     group: "冷凍品", groupEmoji: "🍦", category: "freezer", defaultExpiryDays: 90 },

  // ── 飲み物 ────────────────────────────────────
  // 水・ミネラルウォーター
  { name: "水道水",               group: "飲み物", groupEmoji: "💧", category: "pantry", defaultExpiryDays: 1   },
  { name: "ミネラルウォーター",   group: "飲み物", groupEmoji: "💧", category: "pantry", defaultExpiryDays: 365 },
  { name: "炭酸水",               group: "飲み物", groupEmoji: "🫧", category: "pantry", defaultExpiryDays: 180 },
  { name: "天然水",               group: "飲み物", groupEmoji: "💧", category: "pantry", defaultExpiryDays: 365 },
  // お茶類
  { name: "緑茶",                 group: "飲み物", groupEmoji: "🍵", category: "pantry", defaultExpiryDays: 365 },
  { name: "煎茶",                 group: "飲み物", groupEmoji: "🍵", category: "pantry", defaultExpiryDays: 365 },
  { name: "抹茶",                 group: "飲み物", groupEmoji: "🍵", category: "pantry", defaultExpiryDays: 365 },
  { name: "紅茶",                 group: "飲み物", groupEmoji: "🫖", category: "pantry", defaultExpiryDays: 365 },
  { name: "ウーロン茶",           group: "飲み物", groupEmoji: "🍵", category: "pantry", defaultExpiryDays: 365 },
  { name: "ほうじ茶",             group: "飲み物", groupEmoji: "🍵", category: "pantry", defaultExpiryDays: 365 },
  { name: "麦茶",                 group: "飲み物", groupEmoji: "🍵", category: "pantry", defaultExpiryDays: 365 },
  { name: "ハーブティー",         group: "飲み物", groupEmoji: "🫖", category: "pantry", defaultExpiryDays: 365 },
  { name: "玉露",                 group: "飲み物", groupEmoji: "🍵", category: "pantry", defaultExpiryDays: 365 },
  // ジュース・果実飲料
  { name: "オレンジジュース",     group: "飲み物", groupEmoji: "🍊", category: "fridge", defaultExpiryDays: 7   },
  { name: "りんごジュース",       group: "飲み物", groupEmoji: "🍎", category: "fridge", defaultExpiryDays: 7   },
  { name: "グレープフルーツジュース", group: "飲み物", groupEmoji: "🍋", category: "fridge", defaultExpiryDays: 7 },
  { name: "野菜ジュース",         group: "飲み物", groupEmoji: "🥕", category: "pantry", defaultExpiryDays: 180 },
  { name: "トマトジュース",       group: "飲み物", groupEmoji: "🍅", category: "pantry", defaultExpiryDays: 180 },
  { name: "100%果汁ジュース",     group: "飲み物", groupEmoji: "🍹", category: "pantry", defaultExpiryDays: 180 },
  // 清涼飲料水
  { name: "コーラ",               group: "飲み物", groupEmoji: "🥤", category: "pantry", defaultExpiryDays: 365 },
  { name: "サイダー",             group: "飲み物", groupEmoji: "🫧", category: "pantry", defaultExpiryDays: 365 },
  { name: "ジンジャーエール",     group: "飲み物", groupEmoji: "🥤", category: "pantry", defaultExpiryDays: 365 },
  { name: "スポーツドリンク",     group: "飲み物", groupEmoji: "💦", category: "pantry", defaultExpiryDays: 365 },
  { name: "エナジードリンク",     group: "飲み物", groupEmoji: "⚡", category: "pantry", defaultExpiryDays: 365 },
  { name: "コーヒー（缶）",       group: "飲み物", groupEmoji: "☕", category: "pantry", defaultExpiryDays: 365 },
  { name: "カフェラテ",           group: "飲み物", groupEmoji: "☕", category: "pantry", defaultExpiryDays: 7   },
  { name: "アイスコーヒー",       group: "飲み物", groupEmoji: "☕", category: "fridge", defaultExpiryDays: 5   },
  { name: "アイスティー",         group: "飲み物", groupEmoji: "🧋", category: "fridge", defaultExpiryDays: 5   },
  { name: "ミルクティー",         group: "飲み物", groupEmoji: "🧋", category: "fridge", defaultExpiryDays: 5   },
  { name: "甘酒",                 group: "飲み物", groupEmoji: "🍶", category: "pantry", defaultExpiryDays: 180 },
  // アルコール飲料
  { name: "ビール",               group: "飲み物", groupEmoji: "🍺", category: "fridge", defaultExpiryDays: 180 },
  { name: "日本酒",               group: "飲み物", groupEmoji: "🍶", category: "fridge", defaultExpiryDays: 365 },
  { name: "焼酎",                 group: "飲み物", groupEmoji: "🥃", category: "pantry", defaultExpiryDays: 730 },
  { name: "赤ワイン",             group: "飲み物", groupEmoji: "🍷", category: "pantry", defaultExpiryDays: 730 },
  { name: "白ワイン",             group: "飲み物", groupEmoji: "🍷", category: "fridge", defaultExpiryDays: 7   },
  { name: "ロゼワイン",           group: "飲み物", groupEmoji: "🍷", category: "fridge", defaultExpiryDays: 7   },
  { name: "ウイスキー",           group: "飲み物", groupEmoji: "🥃", category: "pantry", defaultExpiryDays: 730 },
  { name: "ウォッカ",             group: "飲み物", groupEmoji: "🥃", category: "pantry", defaultExpiryDays: 730 },
  { name: "シャンパン",           group: "飲み物", groupEmoji: "🍾", category: "fridge", defaultExpiryDays: 30  },
  { name: "リキュール",           group: "飲み物", groupEmoji: "🥃", category: "pantry", defaultExpiryDays: 730 },
  { name: "梅酒",                 group: "飲み物", groupEmoji: "🍶", category: "pantry", defaultExpiryDays: 730 },
  { name: "チューハイ",           group: "飲み物", groupEmoji: "🍺", category: "fridge", defaultExpiryDays: 180 },
  { name: "発泡酒",               group: "飲み物", groupEmoji: "🍺", category: "fridge", defaultExpiryDays: 180 },
];

export function searchMaster(query: string, group: string): MasterItem[] {
  const q = query.trim().toLowerCase();
  return FOOD_MASTER.filter((item) => {
    const matchGroup = group === "すべて" || item.group === group;
    const matchQuery = !q || item.name.toLowerCase().includes(q);
    return matchGroup && matchQuery;
  });
}
